# Generated by Django 4.1.5 on 2023-03-07 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='ism',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profil',
            name='jins',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
