# Generated by Django 4.1.5 on 2023-03-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_izoh'),
    ]

    operations = [
        migrations.AddField(
            model_name='izoh',
            name='sana',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
